services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai-productivity-backend-prod
    ports:
      - "8000:8000"
    environment:
      - DEBUG=false
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here-use-secrets-module-to-generate}
      - INSECURE_COOKIES=false
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
