services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai-productivity-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=true
      - SECRET_KEY=dev-secret-key-change-in-production
      # Allow auth cookies to be sent over HTTP during local development.
      # In production this variable should be omitted so the cookie is marked
      # as Secure.  See backend app.config.Settings.insecure_cookies.
      - INSECURE_COOKIES=true
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ai-productivity-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DOCKER_ENV=true
      # Frontend (inside container) must talk to backend service via its Docker
      # network alias "backend" rather than localhost.
      - VITE_API_URL=http://backend:8000
    networks:
      - app-network
    depends_on:
      - backend
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  data:
    driver: local
