version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai-productivity-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - ./backend/alembic:/app/alembic
      - ./backend/tests:/app/tests
      - ./backend/data:/app/data
      - ./backend/requirements.txt:/app/requirements.txt
      - ./backend/alembic.ini:/app/alembic.ini
    environment:
      - DEBUG=true
      - SECRET_KEY=dev-secret-key-change-in-production
      - OPENAI_API_KEY=dummy-key-for-testing
      # Allow auth cookies to be sent over HTTP during local development.
      # In production this variable should be omitted so the cookie is marked
      # as Secure.  See backend app.config.Settings.insecure_cookies.
      - INSECURE_COOKIES=true
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ai-productivity-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
      - ./frontend/vite.config.js:/app/vite.config.js
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DOCKER_ENV=true
      # Frontend (inside container) must talk to backend service via its Docker
      # network alias "backend" rather than localhost.
      # For production deployment, set VITE_API_URL to https://yourdomain.com/api
      - VITE_API_URL=${VITE_API_URL:-http://backend:8000}
    networks:
      - app-network
    depends_on:
      - backend
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
