services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai-productivity-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - ./backend/alembic:/app/alembic
      - ./backend/tests:/app/tests
      - ./backend_data:/data
      - ./backend/requirements.txt:/app/requirements.txt
      - ./backend/alembic.ini:/app/alembic.ini
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: ai-productivity-redis
    command: ["redis-server", "--save", ""]   # no RDB dump for dev speed
    volumes:
      - redis_data:/data
    ports:
      - "6380:6379"
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ai-productivity-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
      - ./frontend/vite.config.js:/app/vite.config.js
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DOCKER_ENV=true
      # Frontend (inside container) must talk to backend service via its Docker
      # network alias "backend" rather than localhost.
      # For production deployment, set VITE_API_URL to https://yourdomain.com/api
      - VITE_API_URL=${VITE_API_URL:-http://backend:8000}
    networks:
      - app-network
    depends_on:
      - backend
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  redis_data:
    external: true
    name: ai-productivity-app_redis_data
