# Qdrant Vector Database Configuration
# Run with: docker-compose -f docker-compose.qdrant.yml up
version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:v1.7.4
    container_name: ai-productivity-qdrant
    ports:
      - "6333:6333"  # HTTP API
      - "6334:6334"  # gRPC API (optional)
    volumes:
      - ./qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    external: true
    name: ai-productivity-app_app-network
